extends: default
rules:
  indentation:
    spaces: 2
    indent-sequences: false
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  document-start:
    present: false
